server:
  port: SERVER_PORT
  context-path: /frp
  tomcat:
    uri-encoding: UTF-8

spring:
  main: 
    banner-mode: "off"

shiro: 
  filterChainDefinitions: 
    ${adminPath}/third/** = anon

jdbc:
  # Mysql 数据库配置(远程)
  type: mysql
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://MYSQL_HOST:MYSQL_PORT/MYSQL_DB?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
  username: MYSQL_USER
  password: MYSQL_PASSWD


    #jdbc:
  # Mysql 数据库配置(Docker)
  #type: mysql
  #driver: com.mysql.jdbc.Driver
  #url: jdbc:mysql://mysql:3306/frp?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
  #username: docker
  #password: 123456

